# Generated by Django 3.2 on 2022-07-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_apiuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
