# Generated by Django 3.2 on 2022-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_apiuser_last_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='last_api_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
