# Generated by Django 3.2 on 2022-07-28 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_apiuser_last_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
