# Generated by Django 3.2 on 2022-07-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220729_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
