# Generated by Django 3.2 on 2022-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_download_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='downloads',
            field=models.ManyToManyField(blank=True, to='posts.Download'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
