# Generated by Django 3.2 on 2022-08-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_alter_apiuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
