# Generated by Django 3.2 on 2023-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('filter', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('additional_keyword', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
