# Generated by Django 3.2 on 2023-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_searchpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
