# Generated by Django 3.2 on 2023-07-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_searchpage_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('filter', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('additional_keyword', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='SearchPage',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('searchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.searchitem')),
            ],
            bases=('posts.searchitem',),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('searchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.searchitem')),
            ],
            bases=('posts.searchitem',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('searchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.searchitem')),
            ],
            bases=('posts.searchitem',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('searchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.searchitem')),
            ],
            bases=('posts.searchitem',),
        ),
    ]
