# Generated by Django 3.2 on 2023-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20230707_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchitem',
            name='user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
