# Generated by Django 3.2 on 2023-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_apiuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('link_code', models.TextField()),
                ('referral_pattern', models.CharField(max_length=255)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
    ]
