# Generated by Django 3.2 on 2023-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_adlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlink',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adlink',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adlink',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='adlink',
            name='members',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adlink',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
