# Generated by Django 3.2 on 2023-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20230912_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='order_id',
            field=models.CharField(max_length=10),
        ),
    ]
