# Generated by Django 3.2 on 2023-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_referrallink_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
