# Generated by Django 3.2 on 2023-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_referrallink_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('credits_threshold', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PriceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('records', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='apiuser',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='totalCredits',
            field=models.IntegerField(default=0),
        ),
    ]
