# Generated by Django 3.2 on 2023-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20231007_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceDiscount',
        ),
        migrations.AddField(
            model_name='levelthreshold',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
