# Generated by Django 3.2 on 2023-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestzaDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordName', models.CharField(max_length=100)),
                ('wordMention_May_22', models.IntegerField(default=0)),
                ('wordMention_Jun_22', models.IntegerField(default=0)),
                ('wordMention_Jul_22', models.IntegerField(default=0)),
                ('wordMention_Aug_22', models.IntegerField(default=0)),
                ('wordMention_Sep_22', models.IntegerField(default=0)),
                ('wordMention_Oct_22', models.IntegerField(default=0)),
                ('wordMention_Nov_22', models.IntegerField(default=0)),
                ('wordMention_Dec_22', models.IntegerField(default=0)),
                ('wordMention_Jan_23', models.IntegerField(default=0)),
                ('wordMention_Feb_23', models.IntegerField(default=0)),
                ('wordMention_Mar_23', models.IntegerField(default=0)),
                ('wordMention_Apr_23', models.IntegerField(default=0)),
            ],
        ),
    ]
