# Generated by Django 3.2 on 2023-06-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestzaDjango',
            new_name='WordChart',
        ),
    ]
