# Generated by Django 3.2 on 2024-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_order_orderhistory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
