# Generated by Django 3.2 on 2024-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20240329_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='database',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
