# Generated by Django 3.2 on 2024-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_order_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='database',
        ),
        migrations.AddField(
            model_name='order',
            name='tabs',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('database', 'Database')], default='accounts', max_length=20),
        ),
    ]
