# Generated by Django 3.2 on 2024-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20240329_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
